import os
from datetime import datetime, timezone
from openai import OpenAI
from schemas.repo import Repo

STACK_CONTEXT = (
    "Python, TypeScript, Dart/Flutter, Firebase, VS Code extensions, "
    "GitHub Actions, Ollama, local-first AI, WhatsApp integration, "
    "Raspberry Pi, SQLite, Riverpod, FastAPI, Docker"
)
RELEVANCE_THRESHOLD = 0.65


def _cosine_similarity(a: list[float], b: list[float]) -> float:
    """Compute cosine similarity between two vectors."""
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = sum(x ** 2 for x in a) ** 0.5
    norm_b = sum(x ** 2 for x in b) ** 0.5
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


def score_relevance(repos: list[Repo]) -> list[Repo]:
    """Score repos against the tech stack using GitHub Models embeddings.

    Embeds each repo's description + topics and computes cosine similarity
    against the stack context.  Repos scoring >= RELEVANCE_THRESHOLD get a
    one-sentence relevance_reason generated by GPT-4o-mini.
    """
    if not repos:
        return []

    client = OpenAI(
        base_url="https://models.github.ai/inference",
        api_key=os.environ.get("GITHUB_TOKEN", ""),
    )

    # Embed the reference stack once
    stack_resp = client.embeddings.create(
        model="text-embedding-3-small",
        input=STACK_CONTEXT,
    )
    stack_embedding: list[float] = stack_resp.data[0].embedding

    # Embed all repos in a single batch call
    texts = [f"{r.description} {' '.join(r.topics)}" for r in repos]
    repo_resp = client.embeddings.create(
        model="text-embedding-3-small",
        input=texts,
    )

    result: list[Repo] = []
    for i, repo in enumerate(repos):
        repo_embedding: list[float] = repo_resp.data[i].embedding
        raw_score = _cosine_similarity(repo_embedding, stack_embedding)
        # Cosine similarity can be negative; clamp negatives to 0.0 since
        # a negative score indicates no meaningful relevance to the stack.
        rel_score = round(max(0.0, min(1.0, raw_score)), 4)

        reason = ""
        if rel_score >= RELEVANCE_THRESHOLD:
            reason_resp = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {
                        "role": "user",
                        "content": (
                            f"Why is {repo.name} relevant to this stack: "
                            f"{STACK_CONTEXT}? One sentence."
                        ),
                    }
                ],
                max_tokens=100,
            )
            reason = (reason_resp.choices[0].message.content or "").strip()

        result.append(repo.model_copy(update={
            "relevance_score": rel_score,
            "relevance_reason": reason,
        }))

    return result


def score_and_rank(repos: list[Repo], top_n: int = 5) -> list[Repo]:
    """Score and rank repos. Returns top_n sorted by score descending."""
    if not repos:
        return []

    max_delta = max((r.stars_delta for r in repos), default=1) or 1
    scored = []
    for repo in repos:
        delta_score = repo.stars_delta / max_delta
        source_score = min(repo.source_count / 3, 1.0)
        topic_score = min(len(repo.topics) / 5, 1.0)
        age_days = (datetime.now(tz=timezone.utc) - repo.discovered_at).days
        recency_score = 1.0 if age_days <= 30 else 0.0

        final = (
            0.4 * delta_score +
            0.3 * source_score +
            0.2 * topic_score +
            0.1 * recency_score
        )
        scored.append(repo.model_copy(update={"score": round(final, 4)}))

    scored.sort(key=lambda r: r.score, reverse=True)
    return scored[:top_n]
